name: OpenaiGPTLLM
model_id: ${env| model_id, ep-20250214102831-7mfjh}
api_key: ${env| custom_openai_key, openai_api_key}
endpoint: ${env| custom_openai_endpoint, https://api.openai.com/v1}
temperature: 0
vision: false
response_format: json_object
